spring:
  application:
    name: task-tracker-backend

  # Database
  datasource:
    url: jdbc:postgresql://database:5432/task_tracker
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Broker
  kafka:
    bootstrap-servers: broker:29092
    email-sending-tasks-topic: EMAIL_SENDING_TASKS

# Security
security:
  jwt:
    secret_key: ${SECRET_KEY}
    access_token_expiration: 36000000 # 10 hours
    refresh_token_expiration: 252000000 # 7 days

server:
  port: 8080